import {assert,eq,suite,test} from './harness.js';
import * as E from '../js/core/cup-handle.js';
import {initCupRadarTab} from '../js/ui/cup-radar-tab.js';

function fixture(){const levels=[...Array.from({length:24},(_,i)=>100+i*.45),108,105,102,100,98.5,98,98.2,98.5,99,100,102,105,108,110,109,108.5,109,112];let prev=levels[0];return levels.map((v,i)=>{const o=prev;prev=v;return{t:i*900000,end:(i+1)*900000-1,o,h:Math.max(o,v)+.2,l:Math.min(o,v)-.2,c:v,v:i===levels.length-1?2500:1000};});}
export function run(){
 suite('cup and handle radar');
 test('confirmed rounded cup, shallow handle and volume-backed rim close produce a candidate',()=>{const r=E.detect(fixture());eq(r.active.stage,'ENTRY');eq(r.active.leftIndex,23);eq(r.active.bottomIndex,29);eq(r.active.rightIndex,37);eq(r.active.entry,112);assert(r.active.checks.every(x=>x.pass));eq(r.active.levels.targets.length,3);eq(r.active.levels.stop,r.active.handleLow);eq(r.active.levels.measuredTarget,r.active.entry+r.active.cupDepth);});
 test('right-rim recovery appears as a cup watch before enough handle bars form',()=>{const c=fixture();eq(E.detect(c.slice(0,40)).active.stage,'CUP');eq(E.detect(c.slice(0,41)).active.stage,'HANDLE');});
 test('weak volume cannot create a breakout entry',()=>{const c=fixture();c.at(-1).v=1000;const p=E.detect(c).active;assert(p);assert(p.stage!=='ENTRY');assert(p.checks.some(x=>x.id==='volume'&&!x.pass));});
 test('deep handle below the upper half is rejected',()=>{const c=fixture();c[40].l=102;c[40].c=106;const r=E.detect(c);assert(!r.candidates.some(p=>p.leftIndex===23&&p.rightIndex===37&&p.stage==='ENTRY'));});
 test('a sharp V floor does not pass the rounded-cup filter',()=>{const c=fixture(),v=[104,102,100,98,101,104,106,108,109];for(let j=0;j<v.length;j++){const i=25+j,close=v[j];c[i]={...c[i],o:close,h:close+.2,l:close-.2,c:close};}const r=E.detect(c);assert(!r.candidates.some(p=>p.leftIndex===23&&p.rightIndex===37));});
 test('incomplete raw candles are not included and risk levels stay ordered',()=>{const raw=[[0,'10','11','9','10','100',899999],[900000,'10','12','9','11','200',1799999]];eq(E.fromRaw(raw,1000000).length,1);const l=E.levels(112,108,12);assert(l.stop<l.entry&&l.targets[0].price<l.targets[1].price&&l.targets[1].price<l.targets[2].price);});
 test('tab lazily loads cup scanner and accepts only its own same-origin messages',()=>{const events={},sent=[];const frame={dataset:{src:'./cup-radar.html'},contentWindow:{postMessage:(data,origin)=>sent.push({data,origin})},addEventListener(){}};let paused=0,resumed=0;const win={location:{origin:'https://local.test'},addEventListener:(n,f)=>events[n]=f};const tab=initCupRadarTab({document:{getElementById:()=>frame},window:win,isMainBusy:()=>false,pauseMain:()=>paused++,resumeMain:()=>resumed++,shouldResumeMain:()=>true});tab.select(true);eq(frame.src,'./cup-radar.html');eq(paused,1);events.message({data:{type:'qar:cup-busy',busy:true},source:frame.contentWindow,origin:win.location.origin});assert(tab.isBusy());tab.select(false);eq(resumed,0);events.message({data:{type:'qar:cup-busy',busy:false},source:frame.contentWindow,origin:win.location.origin});eq(resumed,1);});
}
