'use strict';
import * as E from '../core/cup-handle.js';
import {intervals,isStale} from '../core/w-scan-state.js';
const $=s=>document.querySelector(s),state={records:new Map(),cache:new Map(),loading:false,mode:'empty',stage:'ALL',offset:0,cooldown:0,lastAuto:0};
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const price=n=>Number.isFinite(n)?n.toLocaleString('en-US',{maximumSignificantDigits:7}):'—';
const time=t=>new Date(t).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
const wait=ms=>new Promise(r=>setTimeout(r,ms)),host={embedded:window.parent!==window,active:window.parent===window,mainBusy:false,otherBusy:false};
function hostBusy(busy){if(host.embedded)window.parent.postMessage({type:'qar:cup-busy',busy},location.origin);}
function status(s,error=false){$('#status').textContent=s;$('#status').style.color=error?'#ff9898':'';}
async function api(path){if(Date.now()<state.cooldown)throw Error('API 제한 대기 중');const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),15000);try{const r=await fetch('https://fapi.binance.com'+path,{signal:ctrl.signal});if(r.status===429||r.status===418){state.cooldown=Date.now()+60000;throw Error('Binance 요청 제한 · 1분 대기');}if(!r.ok)throw Error('시세 요청 실패 · HTTP '+r.status);return await r.json();}finally{clearTimeout(timer);}}
async function candles(sym,tf,now){const key=sym+':'+tf,old=state.cache.get(key)||[],int=intervals[tf],expected=Math.floor(now/int)*int-int;if(old.length&&old.at(-1).t===expected)return old;const gap=old.length?(expected-old.at(-1).t)/int:Infinity,suffix=old.length&&gap<450?'&startTime='+(old.at(-1).t+int):'';const raw=await api(`/fapi/v1/klines?symbol=${encodeURIComponent(sym)}&interval=${tf}&limit=499${suffix}`);if(!Array.isArray(raw))throw Error('캔들 응답 오류');const c=E.validate((suffix?[...old,...E.fromRaw(raw,now)]:E.fromRaw(raw,now)).slice(-499),int);if(c.at(-1)?.t!==expected)throw Error('최신 완성 봉 미수신');state.cache.set(key,c);return c;}
async function scan(){if(!host.active||host.mainBusy||host.otherBusy){status('다른 스캐너 작업 완료 후 시작하세요.');return;}if(state.loading||Date.now()<state.cooldown)return;state.loading=true;$('#scan').disabled=$('#scope').disabled=true;$('#progress').style.display='block';hostBusy(true);status('거래 가능한 USDT 무기한 종목 확인 중');let done=0,failed=0;
 try{const [ex,tickers,clock]=await Promise.all([api('/fapi/v1/exchangeInfo'),api('/fapi/v1/ticker/24hr'),api('/fapi/v1/time')]);const now=Number(clock.serverTime);if(!Number.isFinite(now))throw Error('거래소 시각 확인 실패');state.offset=now-Date.now();const allowed=new Set(ex.symbols.filter(x=>x.status==='TRADING'&&x.contractType==='PERPETUAL'&&x.quoteAsset==='USDT').map(x=>x.symbol));const symbols=tickers.filter(x=>allowed.has(x.symbol)&&+x.quoteVolume>0).sort((a,b)=>+b.quoteVolume-+a.quoteVolume).slice(0,+$('#scope').value).map(x=>x.symbol);const jobs=symbols.flatMap(sym=>['15m','1h'].map(tf=>({sym,tf,key:sym+':'+tf})));const keys=new Set(jobs.map(x=>x.key));for(const [key,r] of state.records)if(!keys.has(key)&&!r.candidates?.length){state.records.delete(key);state.cache.delete(key);}let k=0;
  async function worker(){while(k<jobs.length){const j=jobs[k++];try{const c=await candles(j.sym,j.tf,now),d=E.detect(c);state.records.set(j.key,{...j,c,...d,checked:now,error:null});}catch(e){failed++;const r=state.records.get(j.key);state.records.set(j.key,{...j,c:r?.c||[],candidates:r?.candidates||[],checked:now,error:e.message});}done++;$('#progress').value=done/jobs.length*100;status(`스캔 ${done}/${jobs.length} · 상위 ${symbols.length}종목 · 15분/1시간`);await wait(120);}}
  await Promise.all(Array.from({length:4},worker));state.mode='live';state.lastAuto=Math.floor(now/intervals['15m']);$('#updated').textContent='마지막 확인 '+time(now);status(`완료 · ${symbols.length}종목, 두 시간봉 확인${failed?' · 실패 '+failed+'건':''}`,failed>0);
 }catch(e){status(e.message,true);}finally{state.loading=false;$('#scan').disabled=!host.active||host.mainBusy;$('#scope').disabled=false;$('#progress').style.display='none';hostBusy(false);render();}}
function chart(r,p){const offset=Math.max(0,Math.min(p.leftIndex,r.c.length-70)),c=r.c.slice(offset),W=600,H=150,L=12,R=12,T=12,B=15,lo=Math.min(...c.map(x=>x.l),p.cupBottom),hi=Math.max(...c.map(x=>x.h),p.rim),pad=(hi-lo)*.12||1,min=lo-pad,max=hi+pad,x=i=>L+(i-offset+.5)*(W-L-R)/c.length,y=v=>T+(max-v)/(max-min)*(H-T-B),bw=Math.max(1,Math.min(5,(W-L-R)/c.length*.5));let s=`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(r.sym)} 컵앤핸들 차트">`;for(let i=offset;i<r.c.length;i++){const b=r.c[i],xx=x(i),color=b.c>=b.o?'#609e8d':'#9a6973';s+=`<line x1="${xx}" x2="${xx}" y1="${y(b.h)}" y2="${y(b.l)}" stroke="${color}"/><rect x="${xx-bw/2}" y="${Math.min(y(b.o),y(b.c))}" width="${bw}" height="${Math.max(1,Math.abs(y(b.o)-y(b.c)))}" fill="${color}"/>`;}s+=`<line x1="${L}" x2="${W-R}" y1="${y(p.rim)}" y2="${y(p.rim)}" stroke="#e9c078" stroke-dasharray="5 4"/><polyline points="${[[p.leftIndex,p.cupLeft],[p.bottomIndex,p.cupBottom],[p.rightIndex,p.cupRight],...(p.handleIndex>=0?[[p.handleIndex,p.handleLow]]:[])].map(([i,v])=>`${x(i)},${y(v)}`).join(' ')}" fill="none" stroke="#6ee7b7" stroke-width="2"/>`;if(p.entry)s+=`<circle cx="${x(r.c.length-1)}" cy="${y(p.entry)}" r="4" fill="#6ee7b7"/>`;return s+'</svg>';}
function rows(){return[...state.records.values()].flatMap(r=>(r.candidates||[]).map(p=>({r,p})));}
function card({r,p}){const stale=state.mode==='live'&&isStale(r,Date.now()+state.offset),badge={CUP:'컵 형성',HANDLE:'핸들 지지',ENTRY:'돌파 타점',FILTERED:'필터 제외'}[p.stage]||p.stage,lev=p.levels;return `<article class="card ${p.stage.toLowerCase()}"><div class="head"><div><b>${esc(r.sym.replace('USDT',''))}</b><small>${r.tf==='15m'?'15분봉':'1시간봉'}</small></div><span class="badge ${p.stage}">${badge}</span></div>${chart(r,p)}<div class="metrics"><div><span>컵 왼쪽 림</span><b>${price(p.cupLeft)}</b></div><div><span>컵 바닥</span><b>${price(p.cupBottom)}</b></div><div><span>오른쪽 림</span><b>${price(p.rim)}</b></div><div><span>컵 깊이</span><b>${(p.cupDepth/p.rim*100).toFixed(2)}%</b></div><div><span>핸들 저점</span><b>${price(p.handleLow)}</b></div><div><span>최신 완성 봉</span><b>${time(r.c.at(-1)?.end)}</b></div></div><div class="reason">${stale?'갱신 필요 · 이전 완성 봉 결과':esc(p.reason||'구조 검증 통과 · 림 돌파 대기')}<br>${(p.checks||[]).filter(x=>!x.pass).map(x=>esc(x.label)+': '+esc(x.value)).join(' · ')||'형태 필터 통과'}</div>${lev?`<div class="levels"><div class="stop"><span>손절 · 핸들 저점</span><b>${price(lev.stop)}</b></div><div><span>TP1 · 1R</span><b>${price(lev.targets[0].price)}</b></div><div><span>TP2 · 2R</span><b>${price(lev.targets[1].price)}</b></div><div><span>TP3 · 3R</span><b>${price(lev.targets[2].price)}</b></div></div><div class="foot">측정 목표 ${price(lev.measuredTarget)} · TP/R 수치는 참고 기준</div>`:''}<div class="foot">${r.error?'갱신 오류: '+esc(r.error):'완성 캔들 기준'} · <a target="_blank" rel="noopener noreferrer" href="https://www.tradingview.com/chart/?symbol=BINANCE%3A${encodeURIComponent(r.sym)}.P&interval=${r.tf==='15m'?'15':'60'}">TradingView ↗</a></div></article>`;}
function render(){const all=rows(),active=all.filter(x=>['CUP','HANDLE','ENTRY'].includes(x.p.stage));for(const s of ['CUP','HANDLE','ENTRY'])$('#count'+s).textContent=active.filter(x=>x.p.stage===s).length;const q=$('#query').value.trim().toUpperCase(),tf=$('#tf').value;const shown=all.filter(({r,p})=>(state.stage==='ALL'||p.stage===state.stage)&&(tf==='ALL'||tf===r.tf)&&r.sym.includes(q)).sort((a,b)=>({ENTRY:0,HANDLE:1,CUP:2}[a.p.stage]-({ENTRY:0,HANDLE:1,CUP:2}[b.p.stage]))||b.p.rightIndex-a.p.rightIndex);$('#results').innerHTML=shown.length?shown.map(card).join(''):`<div class="empty">${state.mode==='empty'?'시장 스캔을 눌러 15분봉과 1시간봉의 컵앤핸들 후보를 찾으세요.':'필터 조건에 맞는 컵앤핸들 후보가 없습니다.'}</div>`;}
document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{state.stage=b.dataset.stage;document.querySelectorAll('[data-stage]').forEach(x=>x.classList.toggle('active',x===b));render();});$('#scan').onclick=scan;$('#tf').onchange=$('#query').oninput=render;$('#auto').onchange=()=>{if($('#auto').checked&&!state.loading)scan();};
 setInterval(()=>{if(host.active&&!host.mainBusy&&!host.otherBusy&&!document.hidden&&$('#auto').checked&&!state.loading&&state.mode==='live'&&Math.floor((Date.now()+state.offset)/intervals['15m'])>state.lastAuto)scan();},15000);
window.addEventListener('message',e=>{if(!host.embedded||e.source!==window.parent||e.origin!==location.origin||e.data?.type!=='qar:cup-context')return;host.active=e.data.active===true;host.mainBusy=e.data.mainBusy===true;if(typeof e.data.otherBusy==='boolean')host.otherBusy=e.data.otherBusy;if(!state.loading)$('#scan').disabled=!host.active||host.mainBusy||host.otherBusy;});
if(host.embedded){$('#scan').disabled=true;window.parent.postMessage({type:'qar:cup-ready'},location.origin);}render();
